[git]
sign-commits = true

[user]
name = "St√©phane Klein"
email = "contact@stephane-klein.info"

[ui]
default-command = "log"
pager = "delta"
diff-formatter = ":git"

[merge-tools]
diff-args = ["--line-numbers", "--side-by-side", "--navigate", "$left", "$right"]
delta.diff-expected-exit-codes = [0, 1]

[aliases]
move-main = ["bookmark", "set", "main", "-r"]
push-main = ["git", "push", "--bookmark", "main"]
all = ["log", "-r", "all()"]
recent = ["log", "-r", "ancestors(@)", "--limit", "20"]

